### ISSUE TITLE
unpaid invoices + ugly traceback

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#119]
blue: 
macos+python+0.6.0-dev: 
Title: unapid invoices + ugly traceback
!!! attach blender-yapapi.log, zipped data-dir !!!

```
[2021-06-01 12:40:14,356 INFO yapapi.executor] Waiting for Golem services to finish...
[2021-06-01 12:40:24,361 INFO yapapi.executor] 3 agreements still unpaid, waiting for invoices...
[2021-06-01 12:40:54,365 WARNING yapapi.executor] Unpaid agreements: {'fcf75f87b1750ab747d568f44fbbbe07bdb57a61c67e42305ade036fdb73efc6', '8de5f2bf399895e27c25e4959511499e1182fcd69cdb83c29f064bbe11a73688', '022ea8cf73ee7b9b06a7e6e65a479e5abe7e349405e3a555f7c7ee4cb668ef9c'}
[2021-06-01 12:40:54,412 INFO yapapi.summary] Total cost: 0
[2021-06-01 12:40:54,413 INFO yapapi.summary] Executor has shut down
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Golem.process_invoices() done, defined at /Users/blue/yapapi/yapapi/executor/__init__.py:374> exception=ServerDisconnectedError('Server disconnected')>
Traceback (most recent call last):
  File "/Users/blue/yapapi/yapapi/executor/__init__.py", line 375, in process_invoices
    async for invoice in self._payment_api.incoming_invoices():
  File "/Users/blue/yapapi/yapapi/rest/payment.py", line 217, in fetch
    events = await api.get_invoice_events(after_timestamp=ts)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/api_client.py", line 194, in __call_api
    response_data = await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/rest.py", line 192, in GET
    return await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

[Uploading blender-yapapi-2021-06-01_12.39.34.log…]()
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/6576138/yagna_rCURRENT.log)

**Comment by mateuszsrebrny** [comment]
closed via https://github.com/golemfactory/yapapi/pull/423
