### ISSUE TITLE
Crash: Error when shutting down Executor: Server disconnected    

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#131]
Seems this is not handled in yapapi, therefore crashes the whole `async with Executor`

```
DEBUG:yapapi.events:ShutdownFinished(exc_info=(<class 'aiohttp.client_exceptions.ServerDisconnectedError'>, ServerDisconnectedError('Server disconnected'), <traceback object
 at 0x7f9282da6a50>))                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                           
  File "/root/miniconda3/envs/rdkit/lib/python3.7/contextlib.py", line 661, in __aexit__                                                                                     
    cb_suppress = await cb(*exc_details)                                                                                                                                     
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 291, in _shutdown                                                                    
    await asyncio.wait_for(self._process_invoices_job, timeout=30)                                                                                                           
  File "/root/miniconda3/envs/rdkit/lib/python3.7/asyncio/tasks.py", line 442, in wait_for                                                                                   
    return fut.result()                                                                                                                                                      
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 366, in _process_invoices                                                            
    async for invoice in self._payment_api.incoming_invoices():                                                                                                              
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 225, in fetch                                                                  
    invoice = await self.invoice(ev.invoice_id)                                                                                                                              
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 204, in invoice                                                                
    invoice_obj = await self._api.get_invoice(invoice_id)                                                                                                                    
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api                                                           
    _request_timeout=_request_timeout,                                                                                                                                       
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 198, in GET                                                                        
    query_params=query_params,                                                                                                                                               
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 170, in request                                                                    
    r = await self.pool_manager.request(**args)                                                                                                                              
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request                                                                    
    await resp.start(conn)                                                                                                                                                   
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 890, in start                                                                
    message, payload = await self._protocol.read()  # type: ignore                                                                                                           
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/streams.py", line 604, in read                                                                       
    await self._waiter                                            
```

**Comment by azawlocki** [comment]
@mbenke We have a regression in `yapapi-0.6.0` -- payment API calls are not repeated on errors. Upcoming `0.6.1` release will fix this (again). You may also install our `0.6.1a0` pre-release in which this is fixed, with:
```
pip install --extra-index-url https://test.pypi.org/simple/ yapapi==0.6.1a0
```

**Comment by mbenke** [comment]
@azawlocki Thanks! I'll try this. Maybe this will help alleviate some problems described in #132 (cc @nieznanysprawiciel )

**Comment by mbenke** [comment]
@azawlocki I can now see the retries in the log, but the end effect is similar:

```
DEBUG:yapapi.events:DebitNoteReceived(agr_id='10b5450179940db81edadd4b3c58a0cca29e082076cd7a83c95e5384e3d49323', note_id='eb61e2ef-5777-4f65-8e4d-3599e65064fe', amount='0.2911224946422139')  
DEBUG:yapapi.rest.common:API call timed out (attempt 1/5), retrying in 1.0 s
NoneType: None
DEBUG:yapapi.rest.common:API call timed out (attempt 2/5), retrying in 1.0 s                                                                                  
NoneType: None                                                           
DEBUG:yapapi.rest.common:API call timed out (attempt 3/5), retrying in 1.0 s
NoneType: None         
DEBUG:yapapi.rest.common:API call timed out (attempt 4/5), retrying in 1.0 s
NoneType: None         
DEBUG:yapapi.rest.common:API call timed out (attempt 5/5), giving up                                                                                                        
DEBUG:yapapi.rest.payment:Received debit note event: {'debit_note_id': '312daf4d-1897-4f0f-bdcb-04fe3f40379c',
 'event_date': datetime.datetime(2021, 6, 23, 9, 41, 2, 747000, tzinfo=tzutc())}, type: <class 'yapapi.rest.configuration._DebitNoteReceivedEventWithDate'>
DEBUG:yapapi.events:PaymentFailed(agr_id='10b5450179940db81edadd4b3c58a0cca29e082076cd7a83c95e5384e3d49323', exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f90955c45f0>))                                                                                                                              
Traceback (most recent call last):                                                                                                                                          
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 425, in _process_debit_notes                                                        
    amount=debit_note.total_amount_due, allocation=allocation                                                                                                               
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/common.py", line 87, in wrapper                                                                 
    raise se.exception
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/common.py", line 78, in wrapper
    return await func(*args, **kwargs)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 36, in accept
    await self._api.accept_debit_note(self.debit_note_id, acceptance)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 276, in POST
    body=body,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '53', 'Content-Type': 'application/json', 'Date': 'Wed, 23 Jun 2021 09:41:56 GMT')>
HTTP response body: {"message":"Timeout sending Invoice to remote Node."}
```
