### ISSUE TITLE
0 tasks computed?

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#138]
Possibly two issues 
- [] why 0 tasks computed
- [] why yapapi declared success :)

Name: Gert-Jan
yagna version: 0.7.2-rc2
OS+lang+version (if applicable): python macos
Title:  0 tasks computed?

[blender-yapapi-2021-07-06_12.27.57.log](https://github.com/golemfactory/yapapi/files/6769694/blender-yapapi-2021-07-06_12.27.57.log)
[yagna_rCURRENT (8).log](https://github.com/golemfactory/yapapi/files/6769695/yagna_rCURRENT.8.log)

```
0 tasks computed, total time: 0:02:44.887503
```

**Comment by maaktweluit** [comment]
@shadeofblue i don't get it, when running yapapi it should compute 6 tasks..

Providers will have network issues, yapapi should pick another provider to do the work

**Comment by azawlocki** [comment]
@maaktweluit  @mateuszsrebrny  @shadeofblue 
Premature `yapapi` shutdown is caused by an unhandled `Connection reset by peer` error when making a REST API request to the requestor `yagna` daemon. This is most probably caused by a heavy load of the daemon or the whole machine on which the requestor app and/or the daemon runs.

This is not a regression and is not related to any recent changes in `yapapi`, and therefore, IMO, should not block the next release.


Details (from the attached log file):
```
[2021-07-06T12:30:45.871+0200 DEBUG yapapi.events] ComputationFinished(job_id='b99a2b36-be7a-4092-bb6a-5f75cf98ffa9', exc_info=(<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(54, 'Connection reset by peer'), <traceback object at 0x103d7f780>))
Traceback (most recent call last):
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/executor/__init__.py", line 435, in _submit
    raise cast(BaseException, task.exception())
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/executor/__init__.py", line 374, in worker_starter
    await job.agreements_pool.cycle()
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/agreements_pool.py", line 60, in cycle
    await self.release_agreement(
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/agreements_pool.py", line 172, in release_agreement
    await self._terminate_agreement(agreement_id, reason)
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/agreements_pool.py", line 184, in _terminate_agreement
    agreement_details = await buffered_agreement.agreement.details()
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/yapapi/rest/market.py", line 63, in details
    return AgreementDetails(_ref=await self._api.get_agreement(self._id))
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/ya_market/rest.py", line 192, in GET
    return await self.request(
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/ya_market/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/Users/mwu-gol/src/yapapi/.venv/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
[2021-07-06T12:30:45.874+0200 ERROR yapapi.summary] Computation failed, reason: [Errno 54] Connection reset by peer
```

**Comment by azawlocki** [comment]
Fixed in the release branch of `yapapi` (`b0.6`) by https://github.com/golemfactory/yapapi/pull/535
