### ISSUE TITLE
Failed to start instances after 240 seconds

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#147]
Name: Mateusz
yagna version: v0.8.0-rc5
OS+lang+version (if applicable): win
[yagna_rCURRENT (9).log](https://github.com/golemfactory/yagna-triage/files/7243582/yagna_rCURRENT.9.log)
[http-proxy-2021-09-28_09.00.58.log](https://github.com/golemfactory/yagna-triage/files/7243583/http-proxy-2021-09-28_09.00.58.log)

```
[2021-09-28T09:00:58.559+0200 INFO yapapi] Using log file `http-proxy-2021-09-28_09.00.58.log`; in case of errors look for additional information there
yapapi version: 0.7.0a0
Using subnet: devnet-beta.2, payment driver: zksync, and network: rinkeby

instances: []
[2021-09-28T09:01:03.254+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'etam.b2'
[2021-09-28T09:01:03.549+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider 'etam.b2'
[2021-09-28T09:01:03.560+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'qbam.b2'
[2021-09-28T09:01:03.936+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider 'qbam.b2'
[2021-09-28T09:01:04.403+0200 INFO yapapi.summary] [Job 1] Task started on provider 'etam.b2', task data: Service: HttpService
[2021-09-28T09:01:04.405+0200 INFO yapapi.services] <HttpService on etam.b2 [ 0x0d54c722ede3821b6e9542475fae060844a27766 ]> commissioned
[2021-09-28T09:01:04.805+0200 INFO yapapi.summary] [Job 1] Task started on provider 'qbam.b2', task data: Service: HttpService
[2021-09-28T09:01:04.808+0200 INFO yapapi.services] <HttpService on qbam.b2 [ 0x487268e11274c3bcefd634f771f2a01a4c606d31 ]> commissioned
[2021-09-28T09:01:05.231+0200 INFO yapapi.summary] Received proposals from 10 providers so far
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
instances: ['etam.b2: running', 'qbam.b2: starting']
[2021-09-28T09:05:12.802+0200 INFO yapapi.summary] [Job 1] Terminated agreement with etam.b2
[2021-09-28T09:05:12.896+0200 INFO yapapi.summary] [Job 1] Terminated agreement with qbam.b2
[2021-09-28T09:05:13.115+0200 INFO yapapi.executor] Golem is shutting down...
[2021-09-28T09:05:13.115+0200 INFO yapapi.executor] All jobs have finished
[2021-09-28T09:05:13.122+0200 INFO yapapi.executor] 2 agreements still unpaid, waiting for invoices...
[2021-09-28T09:05:13.773+0200 INFO yapapi.summary] [Job 1] Accepted invoice from 'etam.b2', amount: 0.0126016636626
[2021-09-28T09:05:13.857+0200 INFO yapapi.summary] [Job 1] Accepted invoice from 'qbam.b2', amount: 0.01260069691765
[2021-09-28T09:05:13.857+0200 INFO yapapi.executor] Waiting for Golem services to finish...
[2021-09-28T09:05:13.871+0200 INFO yapapi.summary] Total cost: 0.02520236058025
[2021-09-28T09:05:13.871+0200 ERROR yapapi.summary] Error when shutting down Golem engine: Failed to start instances after 240.0 seconds
Traceback (most recent call last):
  File "http_proxy.py", line 225, in <module>
    run_golem_example(
  File "D:\devel\yapapi\examples\utils.py", line 85, in run_golem_example
    loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "http_proxy.py", line 170, in main
    raise Exception(
Exception: Failed to start instances after 240.0 seconds
Task was destroyed but it is pending!
task: <Task pending name='Task-111' coro=<<async_generator_asend without __name__>()> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000223EF845A90>()]>>

(yagna-python-tutorial) D:\devel\yapapi\examples\http-proxy>
```

**Comment by mfranciszkiewicz** [comment]
https://github.com/golemfactory/yagna/issues/1609

**Comment by mateuszsrebrny** [comment]
@mfranciszkiewicz SDK team says it happens from time to time. Definately more than once. So it is closer to blocking the release than we discussed in the morning)
