### ISSUE TITLE
504 when connecting to http_proxy url

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#148]
Name: Mateusz
yagna version: v0.8.0-rc5
OS+lang+version (if applicable): win

[http-proxy-2021-09-28_08.53.53.log](https://github.com/golemfactory/yagna-triage/files/7243636/http-proxy-2021-09-28_08.53.53.log)
[yagna_r2021-09-28_08-58-14.log](https://github.com/golemfactory/yagna-triage/files/7243637/yagna_r2021-09-28_08-58-14.log)

```
['q53.b2: running', 'michal.b2: running']
local HTTP request: {}
sending a remote request to <HttpService on q53.b2 [ 0xdd91f596223d4ef095e6a96a14d50eb71c6a39b7 ]>
remote headers: b'HTTP/1.1 200 OK\r\nServer: nginx/1.20.1\r\nDate: Tue, 28 Sep 2021 06:54:20 GMT\r\nContent-Type: text/html\r\nContent-Length: 47\r\nLast-Modified: Tue, 28 Sep 2021 06:54:02 GMT\r\nConnection: close\r\nETag: "6152bc0a-2f"\r\nAccept-Ranges: bytes\r\n\r\n'
remote content: b'Hello from inside Golem!\n... running on q53.b2\n'
local response: Hello from inside Golem!
... running on q53.b2

local HTTP request: {}
sending a remote request to <HttpService on michal.b2 [ 0x31b6ab7808f5d0b847344303457117f022735078 ]>
['q53.b2: running', 'michal.b2: running']
Error handling request
Traceback (most recent call last):
  File "C:\Users\golem-User\.envs\yagna-python-tutorial\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "http_proxy.py", line 52, in request_handler
    response = await instance.handle_request(request.path_qs)
  File "http_proxy.py", line 115, in handle_request
    async with ws_session.ws_connect(
  File "C:\Users\golem-User\.envs\yagna-python-tutorial\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\golem-User\.envs\yagna-python-tutorial\lib\site-packages\aiohttp\client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 504, message='Invalid response status', url=URL('ws://127.0.0.1:7465/net-api/v1/net/2a107320885346b6aa757ee429126a02/tcp/192.168.0.3/80')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000023617828760>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000236175995E0>, 86186.75)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000023617550E80>
['q53.b2: running', 'michal.b2: running']
['q53.b2: running', 'michal.b2: running']
['q53.b2: running', 'michal.b2: running']
['q53.b2: running', 'michal.b2: running']
['q53.b2: running', 'michal.b2: running']
['q53.b2: running', 'michal.b2: running']
local HTTP request: {}
sending a remote request to <HttpService on q53.b2 [ 0xdd91f596223d4ef095e6a96a14d50eb71c6a39b7 ]>
remote headers: b'HTTP/1.1 200 OK\r\nServer: nginx/1.20.1\r\nDate: Tue, 28 Sep 2021 06:55:24 GMT\r\nContent-Type: text/html\r\nContent-Length: 47\r\nLast-Modified: Tue, 28 Sep 2021 06:54:02 GMT\r\nConnection: close\r\nETag: "6152bc0a-2f"\r\nAccept-Ranges: bytes\r\n\r\n'
remote content: b'Hello from inside Golem!\n... running on q53.b2\n'
local response: Hello from inside Golem!
... running on q53.b2
```

**Comment by johny-b** [comment]
1. I see this quite often
2. I passed all the info I had to @mfranciszkiewicz .
3. If this is not solved in `yagna`, some workaround probably **could** be implemented - either in `yapapi` or in the example itself. But still, it would be better not to have those `504` at all.

**Comment by mfranciszkiewicz** [comment]
https://github.com/golemfactory/yagna/issues/1610
