### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#152]
Name: ederenn
yagna version: v0.8.0-rc5
OS+lang+version (if applicable): windows 10, py, python 3.8.6

```
Task computed: Task(id=5, data=40), result: output_40.png, time: 0:00:04.097077
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[2021-09-28T12:25:32.918+0200 INFO yapapi.summary] [Job 1] Task finished by provider 'sycamore', task data: 40
[2021-09-28T12:25:35.840+0200 INFO yapapi.summary] Received proposals from 13 providers so far
Task computed: Task(id=6, data=50), result: output_50.png, time: 0:04:07.814731
[2021-09-28T12:25:36.293+0200 INFO yapapi.summary] [Job 1] Task finished by provider 'glen', task data: 50
Task computed: Task(id=4, data=30), result: output_30.png, time: 0:04:09.440121
[2021-09-28T12:25:36.340+0200 INFO yapapi.summary] [Job 1] Task finished by provider '2rec-ubuntu', task data: 30
[2021-09-28T12:25:36.340+0200 INFO yapapi.summary] [Job 1] Computation finished in 263.6s
[2021-09-28T12:25:36.340+0200 INFO yapapi.summary] [Job 1] Negotiated 3 agreements with 3 providers
[2021-09-28T12:25:36.340+0200 INFO yapapi.summary] [Job 1] Provider '2rec-ubuntu' computed 2 tasks
[2021-09-28T12:25:36.355+0200 INFO yapapi.summary] [Job 1] Provider 'sycamore' computed 2 tasks
[2021-09-28T12:25:36.355+0200 INFO yapapi.summary] [Job 1] Provider 'glen' computed 2 tasks
[2021-09-28T12:25:37.340+0200 INFO yapapi.executor] [Job 1] Waiting for 1 worker to finish...
[2021-09-28T12:25:38.308+0200 INFO yapapi.executor] [Job 1] Waiting for Executor services to finish...
6 tasks computed, total time: 0:04:26.783614
[2021-09-28T12:25:38.324+0200 INFO yapapi.executor] Golem is shutting down...
[2021-09-28T12:25:38.324+0200 INFO yapapi.executor] All jobs have finished
[2021-09-28T12:25:38.324+0200 INFO yapapi.executor] 3 agreements still unpaid, waiting for invoices...
[2021-09-28T12:25:40.043+0200 INFO yapapi.summary] [Job 1] Accepted invoice from 'sycamore', amount: 0.0144046454593
[2021-09-28T12:25:40.215+0200 INFO yapapi.summary] [Job 1] Accepted invoice from '2rec-ubuntu', amount: 0.0149527652654
[2021-09-28T12:25:40.340+0200 INFO yapapi.summary] [Job 1] Accepted invoice from 'glen', amount: 0.0147559657722
[2021-09-28T12:25:40.340+0200 INFO yapapi.executor] Waiting for Golem services to finish...
[2021-09-28T12:25:40.371+0200 INFO yapapi.summary] Total cost: 0.0441133764969
[2021-09-28T12:25:40.371+0200 INFO yapapi.summary] Golem engine has shut down

C:\Users\ederenn\Projects\yapapi\examples\blender>
```

**Comment by shadeofblue** [comment]
@zakaprov could not reproduce the issue with instructions from @ederenn
