### ISSUE TITLE
Blender finished, but not return to shell

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#17]
Asignee: Artur Zawłocki
Reporter: maaktweluit

This issue happened again very often in the 25-nov, 26-nov and 1-dec testing sessions

Macos Mojave → python 3.6.8

Had to press ctrl + c to exit the script

```jsx
Adding /Users/mwu-gol/src/golem-project/yapapi/examples to sys.path.
yapapi version: 0.4.0a2
Using subnet: community.3
[2020-11-24 12:15:20,280 INFO yapapi.summary] Demand published on the market
[2020-11-24 12:15:20,698 INFO yapapi.summary] Received proposals from 1 providers so far
[2020-11-24 12:15:22,289 INFO yapapi.summary] Agreement proposed to provider 'ferranti.3'
[2020-11-24 12:15:23,394 INFO yapapi.summary] Received proposals from 2 providers so far
[2020-11-24 12:15:23,520 INFO yapapi.summary] Received proposals from 3 providers so far
[2020-11-24 12:15:24,418 INFO yapapi.summary] Agreement confirmed by provider 'ferranti.3'
[2020-11-24 12:15:24,465 INFO yapapi.summary] Received proposals from 4 providers so far
[2020-11-24 12:15:25,327 INFO yapapi.summary] Task sent to provider 'ferranti.3', task data: 0
[2020-11-24 12:15:26,423 INFO yapapi.summary] Agreement proposed to provider 'univac.3'
[2020-11-24 12:15:27,468 INFO yapapi.summary] Agreement confirmed by provider 'univac.3'
[2020-11-24 12:15:28,479 INFO yapapi.summary] Task sent to provider 'univac.3', task data: 10
[2020-11-24 12:15:29,474 INFO yapapi.summary] Agreement proposed to provider 'ada'
[2020-11-24 12:15:32,888 INFO yapapi.summary] Task computed by provider 'ferranti.3', task data: 0
Task computed: Task(id=1, data=0), result: output_0.png, time: 0:00:07.623690
[2020-11-24 12:15:32,949 INFO yapapi.summary] Task sent to provider 'ferranti.3', task data: 20
[2020-11-24 12:15:37,713 INFO yapapi.summary] Task computed by provider 'ferranti.3', task data: 20
Task computed: Task(id=3, data=20), result: output_20.png, time: 0:00:04.824413
[2020-11-24 12:15:37,819 INFO yapapi.summary] Task sent to provider 'ferranti.3', task data: 30
[2020-11-24 12:15:37,976 INFO yapapi.summary] Task computed by provider 'univac.3', task data: 10
Task computed: Task(id=2, data=10), result: output_10.png, time: 0:00:09.626790
[2020-11-24 12:15:38,102 INFO yapapi.summary] Task sent to provider 'univac.3', task data: 40
[2020-11-24 12:15:41,967 INFO yapapi.summary] Task computed by provider 'ferranti.3', task data: 30
Task computed: Task(id=4, data=30), result: output_30.png, time: 0:00:04.255255
[2020-11-24 12:15:42,053 INFO yapapi.summary] Task sent to provider 'ferranti.3', task data: 50
[2020-11-24 12:15:42,623 INFO yapapi.summary] Task computed by provider 'univac.3', task data: 40
Task computed: Task(id=5, data=40), result: output_40.png, time: 0:00:04.646572
[2020-11-24 12:15:43,756 INFO yapapi.summary] Received proposals from 5 providers so far
[2020-11-24 12:15:44,588 INFO yapapi.summary] Received proposals from 5 providers so far
[2020-11-24 12:15:45,223 INFO yapapi.summary] Task computed by provider 'ferranti.3', task data: 50
Wworker-1:  no more frames to render
Wworker-0:  no more frames to render
Task computed: Task(id=6, data=50), result: output_50.png, time: 0:00:03.256450
[2020-11-24 12:15:45,237 INFO yapapi.summary] Computation finished in 25.1s
[2020-11-24 12:15:45,237 INFO yapapi.summary] Negotiated 2 agreements with 2 providers
[2020-11-24 12:15:45,237 INFO yapapi.summary] Provider 'ferranti.3' computed 4 tasks
[2020-11-24 12:15:45,237 INFO yapapi.summary] Provider 'univac.3' computed 2 tasks
[2020-11-24 12:15:45,237 INFO yapapi.summary] Provider 'ada' did not compute any tasks
[2020-11-24 12:15:46,402 INFO yapapi.summary] Total cost: 0.157865846416
[2020-11-24 12:15:48,498 INFO yapapi.summary] Agreement proposed to provider 'eniac.3'
[2020-11-24 12:15:48,623 INFO yapapi.summary] Agreement confirmed by provider 'eniac.3'
Wworker-2:  no more frames to render
^CShutting down gracefully, please wait a few seconds or press Ctrl+C to exit immediately...
Traceback (most recent call last):
  File "blender.py", line 121, in <module>
    loop.run_until_complete(task)
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 7465)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "blender.py", line 131, in <module>
    loop.run_until_complete(task)
  File "/Users/mwu-gol/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "blender.py", line 96, in main
    f"{utils.TEXT_COLOR_CYAN}"
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/yapapi/executor/__init__.py", line 572, in __aexit__
    await self._stack.aclose()
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/async_exit_stack/_async_exit_stack.py", line 150, in aclose
    await self.__aexit__(None, None, None)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/async_exit_stack/_async_exit_stack.py", line 208, in __aexit__
    raise exc_details[1]
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/async_exit_stack/_async_exit_stack.py", line 191, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/yapapi/rest/payment.py", line 90, in __aexit__
    await self._api.release_allocation(self._id)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_payment/rest.py", line 255, in DELETE
    body=body,
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_payment/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/client.py", line 528, in _request
    req, traces=traces, timeout=real_timeout
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 537, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 894, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 1053, in _create_direct_connection
    raise last_exc
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 1034, in _create_direct_connection
    client_error=client_error,
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/connector.py", line 977, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:7465 ssl:default [Connect call failed ('127.0.0.1', 7465)]
Task exception was never retrieved
future: <Task finished coro=<Executor._submit.<locals>.start_worker() done, defined at /Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/yapapi/executor/__init__.py:315> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/yapapi/executor/__init__.py", line 388, in start_worker
    return
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/yapapi/rest/activity.py", line 99, in __aexit__
    await self._api.get_exec_batch_results(self._id, batch_id, timeout=1.0)
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_activity/api_client.py", line 201, in __call_api
    _request_timeout=_request_timeout,
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_activity/rest.py", line 198, in GET
    query_params=query_params,
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/ya_activity/rest.py", line 173, in request
    data = await r.read()
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/streams.py", line 371, in read
    block = await self.readany()
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/streams.py", line 393, in readany
    await self._wait("readany")
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/streams.py", line 307, in _wait
    await waiter
  File "/Users/mwu-gol/src/golem-project/yapapi/.venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by azawlocki** [comment]
The code that closes an activity has been changed in https://github.com/golemfactory/yapapi/pull/204, this error should not happen anymore.
