### ISSUE TITLE
error after pressing ctrl c in  webapp example

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#197]
Name: ederenn
yagna version: yagna 0.10.0-rc15 (160bc5a1 2022-03-14 build #206)
OS+lang+version (if applicable): Win, webapp, python 3.8.6

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
[webapp.log](https://github.com/golemfactory/yagna-triage/files/8253912/webapp.log)
[yagna_r2022-03-15_12-14-53.log](https://github.com/golemfactory/yagna-triage/files/8253913/yagna_r2022-03-15_12-14-53.log)
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/8253918/yagna_rCURRENT.log)

**Comment by nieznanysprawiciel** [comment]
Blocked: waiting for response from SDK team. It seems to be a problem with `yapapi` rather than in `yagna`

**Comment by johny-b** [comment]
@ederenn 
Do you by any chance still have the log file from this run?
Because `webapp.log` contains only screen logs, and without the `debug`-level file it's really hard to say anything.

Assuming we don't have the file, I'd say that:
1. This probably is not connected to `Ctrl+C`, as the error appeared first time much earlier (according to `webapp.log`)
2. I've never seen a similar problem before
3. I'd expect e.g. various connection issues could be the cause

--> I think we should either:
A) find the debug logs
B) try to understand something from `yagna` logs (@nieznanysprawiciel )
C) close the issue and maybe try to remember about it when we a similar problem again

**Comment by ederenn** [comment]
@johny-b no, noting more than I've included
