### ISSUE TITLE
Failed to spawn instance. Error: Permission denied (os error 13)"}

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#211]
Name: ederenn
yagna version: yagna 0.10.0-rc20  
OS+lang+version (if applicable): Win10. + python 3.6.9

```
[2022-03-31T12:50:58.665+0200 ERROR yapapi.services.service_runner] Failed to spawn instance
Traceback (most recent call last):
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/yapapi/services/service_runner.py", line 369, in spawn_instance
await task
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/yapapi/engine.py", line 652, in worker_task
activity = await self.create_activity([agreement.id](http://agreement.id/))
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/yapapi/engine.py", line 633, in create_activity
agreement_id, stream_events=self._stream_output
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/yapapi/rest/activity.py", line 47, in new_activity
activity_id = await self._api.create_activity(agreement_id)
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/ya_activity/api_client.py", line 205, in __call_api
raise e
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/ya_activity/api_client.py", line 201, in __call_api
_request_timeout=_request_timeout,
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/ya_activity/rest.py", line 276, in POST
body=body,
File "/home/ederenn/.envs/yagna-python-tutorial/lib/python3.6/site-packages/ya_activity/rest.py", line 180, in request
raise ApiException(http_resp=r)
ya_activity.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '605', 'Content-Type': 'application/json', 'Date': 'Thu, 31 Mar 2022 10:50:58 GMT')>
HTTP response body: {"message":"Service error: Activity fbc0b8cb15c948dda4cfe9ca4fa8e4d8 was abruptly terminated. Reason: creation failed, message: Error creating activity: CreateActivity { activity_id: \"fbc0b8cb15c948dda4cfe9ca4fa8e4d8\", agreement_id: \"48256d032dbced4d00d504058fd6aa137d6cb9529606e82d81cf8b18be40043d\", requestor_pub_key: None }: Can't create working directory [/ssd2/golem10/.local/share/ya-provider/exe-unit/work/48256d032dbced4d00d504058fd6aa137d6cb9529606e82d81cf8b18be40043d/fbc0b8cb15c948dda4cfe9ca4fa8e4d8] for activity [fbc0b8cb15c948dda4cfe9ca4fa8e4d8]. Error: Permission denied (os error 13)"}

[<DbService pending>]
```
[yagna_rCURRENT (1).log](https://github.com/golemfactory/yagna-triage/files/8389106/yagna_rCURRENT.1.log)

**Comment by ederenn** [comment]
failed to spawn instance, reason request timeout
https://github.com/golemfactory/yagna-triage/issues/214

**Comment by shadeofblue** [comment]
closing as a duplicate
