### ISSUE TITLE
Subscription expired immediately after starting an example

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#223]
Name: ederenn, blue
yagna version: v0.10.1-rc3
OS+lang+version (if applicable): Mac, Windows

Blue logs:

```
Traceback (most recent call last):
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/rest/market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/api_client.py", line 205, in __call_api
    raise e
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 268, in POST
    return await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (410)
Reason: Gone
HTTP response headers: <CIMultiDictProxy('Content-Length': '135', 'Content-Type': 'application/json', 'Date': 'Mon, 06 Jun 2022 10:53:57 GMT')>
HTTP response body: {"message":"Subscription [ae7fb2b9c36f4e0f85ab671807b227fe-2631f5e0111f6caf0dea68ed07433075d31f45707d2e352abf62df425976b5a4] expired."}
```
[yagna_rCURRENT (9).log](https://github.com/golemfactory/yagna-triage/files/8844100/yagna_rCURRENT.9.log)
[scan-yapapi-2022-06-06_12.53.37.log](https://github.com/golemfactory/yagna-triage/files/8844102/scan-yapapi-2022-06-06_12.53.37.log)

ederenn logs:
```
yapapi version: 0.9.2a0
Using subnet: public-beta, payment driver: erc20, and network: polygon

[2022-06-06T12:47:09.163+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'Jefferson' (0x0f42b4bbfb19fce49fe0e95760187b00c6f7d2f8)
[2022-06-06T12:47:09.821+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider 'Jefferson'
[2022-06-06T12:47:10.727+0200 INFO yapapi.summary] Received proposals from 4 providers so far
[2022-06-06T12:47:11.825+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'nsys-axon' (0x7f6e0a248f9d23af9ca5228588d718663864993b)
[2022-06-06T12:47:12.126+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider 'nsys-axon'
[2022-06-06T12:47:13.745+0200 INFO yapapi.summary] Received proposals from 20 providers so far
[2022-06-06T12:47:14.163+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'nnatbzyr' (0xd7289ae9d6d5de69f92e8d6e92107de7d2568b70)
[2022-06-06T12:47:16.749+0200 INFO yapapi.summary] Received proposals from 21 providers so far
Task exception was never retrieved
future: <Task finished name='Task-503' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\ya_market\api_client.py", line 205, in __call_api    raise e
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\ya_market\api_client.py", line 193, in __call_api    response_data = await self.request(
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (410)
Reason: Gone
HTTP response headers: <CIMultiDictProxy('Content-Length': '135', 'Content-Type': 'application/json', 'Date': 'Mon, 06 Jun 2022 10:47:29 GMT')>
HTTP response body: {"message":"Subscription [883a4789e66b4b06933b58440c3090e1-795bd1110d856d4fcb97c613e59ea52da7b956c1a28e5a8b6209e8461ad49fb7] expired."}
```
[yagna_rCURRENT (10).log](https://github.com/golemfactory/yagna-triage/files/8844114/yagna_rCURRENT.10.log)
[blender-yapapi-2022-06-06_12.47.04.log](https://github.com/golemfactory/yagna-triage/files/8844115/blender-yapapi-2022-06-06_12.47.04.log)

**Comment by johny-b** [comment]
@nieznanysprawiciel 

I see a surprising "Subscription expired" quite often in recent days.
So: my guess is that this might not be only "immediately after starting" case, but maybe more like "sometimes at random".

**Comment by nieznanysprawiciel** [comment]
It seems we are not going to investigate this in nearest future, because it has rather low impact
