### ISSUE TITLE
404 GSB error

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna-triage#226]
Why: Requestor couldn't contact provider node and produced the following error
```
[2022-08-31T12:57:53.906+0200 WARNING yapapi.summary] [Job 2] Worker for provider 'kek' failed; reason: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '134', 'Content-Type': 'application/json', 'Date': 'Wed, 31 Aug 2022 10:57:53 GMT')>
HTTP response body: {"message":"GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404"}
```
Provider log:
[yagna-provider-kek.log](https://github.com/golemfactory/yagna-triage/files/9461879/yagna-provider-kek.log)

What:

**Comment by ederenn** [comment]
repeated on requestor's testing session

Name: ederenn
yagna version: 0.11.0-rc9
OS+lang+version (if applicable): Win 10, py


```
[2022-09-01T12:51:34.350+0200 ERROR yapapi.services.service_runner] Unhandled engine error
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\services\service_runner.py", line 279, in _run_instance
    fut_result = yield batch
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 728, in process_batches
    results = await get_batch_results()
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 708, in get_batch_results
    async for event_class, event_kwargs in remote:
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\activity.py", line 267, in __aiter__
    results = await self._get_results(timeout=min(timeout, 5))
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\activity.py", line 242, in _get_results
    raise err
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\activity.py", line 228, in _get_results
    results = await self._activity._api.get_exec_batch_results(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\rest.py", line 192, in GET
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_activity.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '134', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:34 GMT')>
HTTP response body: {"message":"GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404"}

[2022-09-01T12:51:34.350+0200 INFO yapapi.services.service_runner] <SimpleService terminated on adamw [ 0xd78ad96553e33a14dab722c175d3885d66f0b601 ]> decommissioned
[2022-09-01T12:51:34.397+0200 INFO yapapi.summary] [Job 1] Terminated agreement with adamw
[2022-09-01T12:51:34.444+0200 INFO yapapi.services.service_runner] Restarting service <SimpleService terminated on adamw [ 0xd78ad96553e33a14dab722c175d3885d66f0b601 ]>
[2022-09-01T12:51:35.491+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'office_8_219' (0x5c5f3fefe262455095d53861ba31ae7c0cb455c3)
instances: ['simple-service-1: pending on adamw']
Task exception was never retrieved
future: <Task finished name='Task-140' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:40 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-ee450b4609dfd468f6d28263b9a95e5c9f2c8652f146d44e10cd334f45444225]. Error: Countering Proposal [R-1aee18061965762346eeaac49a2dddd17d4d817f626ede7e3c5ed68fc7207533] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

[2022-09-01T12:51:41.600+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'office_8_230' (0x7726eae6058e68a0f6ba0e6224bb25e5d3e12ba1)
instances: ['simple-service-1: pending on adamw']
Task exception was never retrieved
future: <Task finished name='Task-148' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:46 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-3e56345600926235d57b6c97e293cfb3df15a4979fa162036fb52daea88aa396]. Error: Countering Proposal [R-aeb94fef2a85a5fe831f1233e366a82c3f57fdee070520b33078800614388fab] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

instances: ['simple-service-1: pending on adamw']
[2022-09-01T12:51:47.678+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'office_8_200' (0xb56a7bf63d6bab1e54fe9aca28cadc0e28c5cdf2)
instances: ['simple-service-1: pending on adamw']
Task exception was never retrieved
future: <Task finished name='Task-156' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:52 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-91a09d9d6a74fb793cf222886ad8c157312d55b11a1249a6f07143ad2fb865e3]. Error: Countering Proposal [R-055f793d5c38bb31838f85b38b2fd4c0b338b8b24a2b953ce7b62f6ceb8ca4ac] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

[2022-09-01T12:51:53.772+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'etam' (0x4d8b65a56e50da27961f0231d20a6c07f9465cc2)
instances: ['simple-service-1: pending on adamw']
Task exception was never retrieved
future: <Task finished name='Task-164' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:58 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-abccc9e5ac7742a258410f6764adc6b6861d9ea2867c0fbfb239a9ed1d03b044]. Error: Countering Proposal [R-26a8c6f987a5d7d66bba3441bdbe55abc668225a5bdc417e29506f103134ee61] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

[2022-09-01T12:51:59.851+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'whirlwind' (0xeb7270a90c11234867a1de661698638670789cfa)
Task exception was never retrieved
future: <Task finished name='Task-172' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:51:59 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-213ef74e50b808a531fcf7ef7152615db1f4fbc5395bb3d9b45926f4cf8efac6]. Error: Countering Proposal [R-dade004e9300b62261a5b6b3b08bc6e23046ec72ce4a6cfc0b749a62ce5fc669] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

[2022-09-01T12:52:00.929+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'office_8_67' (0xe6c8c933d5649b2ceeade80e0d47f0c2270c8dbf)
Task exception was never retrieved
future: <Task finished name='Task-177' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:52:00 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-8842c989ac668f803d7dc35ababd16e1ee8c7e14d746482cb2857aa4515d17e0]. Error: Countering Proposal [R-3cd3fe7de4cedc617aae76ebb787b251d7850ac6fbc8d248a388f98778c1cce6] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}

instances: ['simple-service-1: pending on adamw']
[2022-09-01T12:52:02.007+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider 'witek' (0x45b728612826823971e6075bc6750d6e37fec067)
Task exception was never retrieved
future: <Task finished name='Task-182' coro=<Job._handle_proposal() done, defined at C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py:837> exception=ApiException()>
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 890, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\market.py", line 167, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_market\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '339', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:52:01 GMT')>
HTTP response body: {"message":"Failed to send response for Proposal [R-ec8691e84aba4f26e55055fbe2d1808ed07e6b024bd1f62fe0d9422655fdc796]. Error: Countering Proposal [R-bce59821019b26b4faaeb346fd4a5f36391e76465fd05270fb74565c18efdc9e] GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404.."}
```
[yagna_rCURRENT (12).log](https://github.com/golemfactory/yagna-triage/files/9469747/yagna_rCURRENT.12.log)

**Comment by ederenn** [comment]
repeated on requestor's session
Name: Wojtek
yagna version: 0.11.0-rc9
OS+lang+version (if applicable): Mac OS, py

```
yapapi:
[2022-09-01T12:27:14.948+0200 WARNING yapapi.summary] [Job 2] Worker for provider 'z1' failed; reason: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('content-length': '134', 'content-type': 'application/json', 'date': 'Thu, 01 Sep 2022 10:27:14 GMT')>
HTTP response body: {"message":"GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404"}

yagna:
[2022-09-01T12:27:14.840+0200 DEBUG ya_net::hybrid::service] Local bus handler (0xad1a1cb4ae8e1b12a5e499aaf546514545346f3f -> 0x929e27c1a41f5be20fae73c3dfe5d5a8a247ca73), address: /transfer/net/0x929e27c1a41f5be20fae73c3dfe5d5a8a247ca73/exeunit/f662c3a27c9a4a488c95e1fc92d49baa/GetExecBatchResults, id: 7167648406080197 -> send message to remote (326 B)
[2022-09-01T12:27:14.840+0200 DEBUG ya_relay_client::session] Finding Node info [0x929e27c1a41f5be20fae73c3dfe5d5a8a247ca73], using session fbad2174c7e1c1addcd0ae51d73f2ee9.
[2022-09-01T12:27:14.892+0200 ERROR ya_activity::error] Activity API server error: GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404
[2022-09-01T12:27:14.892+0200 DEBUG actix_web::middleware::logger] Error in response: Gsb(GsbFailure("Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404"))
```
[yagna_rCURRENT.log.zip](https://github.com/golemfactory/yagna-triage/files/9469773/yagna_rCURRENT.log.zip)
[yapapi-2022.09.01_12.24.18.log.zip](https://github.com/golemfactory/yagna-triage/files/9469775/yapapi-2022.09.01_12.24.18.log.zip)

**Comment by ederenn** [comment]
Name: ederenn
yagna version:  0.11.0-rc10
OS+lang+version (if applicable): Win10 
Title:  Failed to find Node on relay server: Request failed with code 404"

```
[2022-09-06T12:38:08.829+0200 INFO yapapi.summary] Received proposals from 28 providers so far
[2022-09-06T12:43:19.940+0200 ERROR yapapi.summary] [Job 2] Failed to accept an invoice or a debit note from 'ProviderInfo(id='0xd1ebd0d9d68f490024e0e26f0b5799d0a8136419', name='rollbbul', subnet_tag='hybrid-mainnet')', reason: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '145', 'Content-Type': 'application/json', 'Date': 'Tue, 06 Sep 2022 10:43:19 GMT')>
HTTP response body: {"message":"Service bus error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request timed out after 3000 ms"}

[2022-09-06T12:43:27.627+0200 WARNING yapapi.summary] [Job 2] Worker for provider 'rollbbul' failed; reason: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '134', 'Content-Type': 'application/json', 'Date': 'Tue, 06 Sep 2022 10:43:27 GMT')>
HTTP response body: {"message":"GSB error: GSB failure: Net: error forwarding message: Failed to find Node on relay server: Request failed with code 404"}

[2022-09-06T12:43:27.846+0200 INFO yapapi.summary] [Job 2] Terminated agreement with rollbbul
```
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/9497496/yagna_rCURRENT.log)
