### ISSUE TITLE
Bad content: Flexbuffer Read Error: InvalidRootWidth"}

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#228]
Name: ederenn
yagna version: 0.11.0-rc9
OS+lang+version (if applicable): Win 10

```
[2022-09-01T12:40:29.770+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider 'witek'
[2022-09-01T12:40:30.614+0200 INFO yapapi.services.service_runner] <SimpleService starting on witek [ 0x45b728612826823971e6075bc6750d6e37fec067 ]> commissioned
[2022-09-01T12:40:30.692+0200 ERROR yapapi.services.service_runner] Unhandled engine error
Traceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\services\service_runner.py", line 279, in _run_instance
    fut_result = yield batch
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\engine.py", line 699, in process_batches
    remote = await activity.send(batch, deadline=batch_deadline)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\yapapi\rest\activity.py", line 86, in send
    batch_id = await self._api.call_exec(self._id, yaa.ExeScriptRequest(text=script_txt))
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\api_client.py", line 205, in __call_api
    raise e
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\rest.py", line 268, in POST
    return await self.request(
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\site-packages\ya_activity\rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_activity.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '103', 'Content-Type': 'application/json', 'Date': 'Thu, 01 Sep 2022 10:40:30 GMT')>
HTTP response body: {"message":"GSB error: Bad request: GSB failure: Bad content: Flexbuffer Read Error: InvalidRootWidth"}
```

**Comment by ederenn** [comment]
[yagna_rCURRENT (12).log](https://github.com/golemfactory/yagna-triage/files/9469737/yagna_rCURRENT.12.log)
