### ISSUE TITLE
Failed to start instance, http proxy example

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#230]
Name: ederenn
yagna version: 0.11.0-rc9, py
OS+lang+version (if applicable): Win 10

```
C:\Users\ederenn\Projects\yapapi\examples\http-proxy>python http_proxy.py --payment-network polygon --subnet-tag hybrid-mainnet --running-time 37000
[2022-09-01T12:46:16.526+0200 INFO yapapi] Using log file `http-proxy-2022-09-01_12.46.16.log`; in case of errors look for additional information there
yapapi version: 0.9.2
Using subnet: hybrid-mainnet, payment driver: erc20, and network: polygon

[2022-09-01T12:46:18.886+0200 INFO yapapi.network] Created network: Network { id: 3dd4768675ae43e7b56ded18228d5a0c, ip: 192.168.0.0, mask: 255.255.255.0}
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
instances: [<HttpService pending>, <HttpService pending>]
[2022-09-01T12:50:19.339+0200 WARNING yapapi.summary] Execution interrupted by Exception
[2022-09-01T12:50:20.105+0200 INFO yapapi.executor] Golem is shutting down...
[2022-09-01T12:50:20.105+0200 INFO yapapi.summary] [Job 1] Job finished in 241.1s
[2022-09-01T12:50:20.105+0200 INFO yapapi.summary] [Job 1] Negotiated 0 agreements with 0 providers
[2022-09-01T12:50:20.105+0200 INFO yapapi.executor] All jobs have finished
[2022-09-01T12:50:20.105+0200 INFO yapapi.executor] Waiting for Golem services to finish...
[2022-09-01T12:50:20.136+0200 INFO yapapi.summary] Total cost: 0
[2022-09-01T12:50:20.136+0200 INFO yapapi.summary] Golem engine has shut down
Traceback (most recent call last):
  File "http_proxy.py", line 191, in <module>
    run_golem_example(
  File "C:\Users\ederenn\Projects\yapapi\examples\utils\__init__.py", line 85, in run_golem_example
    loop.run_until_complete(task)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "http_proxy.py", line 124, in main
    raise Exception(
Exception: Failed to start instances after 240.0 seconds
```

**Comment by ederenn** [comment]
[yagna_rCURRENT (10) (1).log](https://github.com/golemfactory/yagna-triage/files/9470172/yagna_rCURRENT.10.1.log)

**Comment by wkargul** [comment]
This issue has been resolved by ya-runtime-vm update on providers. The old version of VM does not listed vm-capabilities feature in the offers.
