### ISSUE TITLE
delay and dirty output after Ctrl-C in webapp_fileupload while requests are handled

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-triage#233]
Name: blue
yagna version:  yagna 0.12.0-rc4 (37539868 2022-11-09 build #239)
OS+lang+version (if applicable): mac+python+yapapi 0.10.0-alpha.0

```
^CShutting down gracefully, please wait a short while or press Ctrl+C to exit immediately...
[2022-11-10T14:18:06.153+0100 INFO yapapi.summary] Received proposals from 29 providers so far
[2022-11-10T14:18:24.169+0100 INFO yapapi.summary] Received proposals from 33 providers so far
[2022-11-10T14:18:37.286+0100 INFO yapapi.contrib.service.http_proxy] Remote response received. status=200
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10eca27c0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10eca2340>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10ec9ba60>
HTTP server stopped
[<HttpService running on fbwk2t2.h [ 0xa7b0c157b1ca223519e854774b84f9eb5eb3c0d4 ] @ 192.168.0.3>, <DbService running on BHS5-11.h [ 0xe171dbc142980fe1eb01c4e6b03420d7a9811af2 ] @ 192.168.0.2>]
[2022-11-10T14:18:38.658+0100 INFO yapapi.services.service_runner] <HttpService terminated on fbwk2t2.h [ 0xa7b0c157b1ca223519e854774b84f9eb5eb3c0d4 ] @ 192.168.0.3> decommissioned
[2022-11-10T14:18:38.751+0100 INFO yapapi.summary] [Job 2] Terminated agreement with fbwk2t2.h
[2022-11-10T14:18:39.365+0100 INFO yapapi.services.service_runner] <DbService terminated on BHS5-11.h [ 0xe171dbc142980fe1eb01c4e6b03420d7a9811af2 ] @ 192.168.0.2> decommissioned
[2022-11-10T14:18:39.546+0100 INFO yapapi.summary] [Job 1] Terminated agreement with BHS5-11.h
[2022-11-10T14:18:39.884+0100 INFO yapapi.summary] [Job 2] Accepted invoice from 'fbwk2t2.h', amount: 0.02283062712345000
[2022-11-10T14:18:40.045+0100 INFO yapapi.summary] [Job 1] Accepted invoice from 'BHS5-11.h', amount: 0.02232012100125000
[2022-11-10T14:18:43.206+0100 INFO yapapi.network] Removed network: Network { id: 1f8da05db5a94ae482f40d6a47aa9cc7, ip: 192.168.0.0, mask: 255.255.255.0}
[2022-11-10T14:18:43.236+0100 ERROR yapapi.contrib.service.http_proxy] Error receiving remote response. url=/images/redditsave.com_how_qas_test_developers_code-1s4j7dzcize81.mp4, service=<HttpService terminated on fbwk2t2.h [ 0xa7b0c157b1ca223519e854774b84f9eb5eb3c0d4 ] @ 192.168.0.3>, exception=<class 'TypeError'>(can't concat NoneType to bytes) [Traceback (most recent call last):
  File "/Users/blue/yapapi/examples/utils/__init__.py", line 80, in run_golem_example
    loop.run_until_complete(task)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/contrib/service/http_proxy.py", line 157, in handle_request
    response = await response_parser.get_response()
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/contrib/service/http_proxy.py", line 81, in get_response
    self.receive_data(ws_response.data)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/contrib/service/http_proxy.py", line 57, in receive_data
    self.content += data
TypeError: can't concat NoneType to bytes
])
```

**Comment by shadeofblue** [comment]
[webapp-yapapi-2022-11-10_14.11.05.zip](https://github.com/golemfactory/yagna-triage/files/9981056/webapp-yapapi-2022-11-10_14.11.05.zip)
