### ISSUE TITLE
“aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer”  while running the webapp example

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-triage#236]
Name: blue
yagna version: yagna 0.12.0-rc4 (37539868 2022-11-09 build #239)
OS+lang+version (if applicable): mac+python+yapapi 0.10.0-alpha.0
Title: “aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer” 

```
[<DbService pending>]
Exception in callback ServiceRunner.__aenter__.<locals>.raise_if_failed(<Task finishe...set by peer')>) at /Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/services/service_runner.py:118
handle: <Handle ServiceRunner.__aenter__.<locals>.raise_if_failed(<Task finishe...set by peer')>) at /Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/services/service_runner.py:118>
Traceback (most recent call last):
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/engine.py", line 963, in find_offers
    await self._find_offers_for_subscription(subscription)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/engine.py", line 911, in _find_offers_for_subscription
    async for proposal in proposals:
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/rest/market.py", line 239, in events
    proposals = await self._api.collect_offers(self._id, timeout=5, max_events=10)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 192, in GET
    return await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
```

**Comment by shadeofblue** [comment]
[3.zip](https://github.com/golemfactory/yagna-triage/files/9981109/3.zip)

**Comment by shadeofblue** [comment]
it doesn't seem like a yapapi issue

**Comment by shadeofblue** [comment]
I see timeouts like this one:

```
[2022-11-10T13:28:25.614+0100 DEBUG ya_payment.rest] request: {'method': 'GET', 'url': 'http://127.0.0.1:7465/payment-api/v1/debitNoteEvents?afterTimestamp=2022-11-10T12%3A28%3A19.587676%2B00%3A00', 'timeout': 300, 'headers': {'Accept': 'application/json', 'authorization': 'Bearer f819f393b19a4351abf9278c5019bb27', 'User-Agent': 'OpenAPI-Generator//python', 'Content-Type': 'application/json'}}
[2022-11-10T13:28:25.725+0100 DEBUG yapapi.events] ProposalFailed(exception=TimeoutError(), job=Job(id=1), proposal=<yapapi.rest.market.OfferProposal object at 0x10fecb730>)
Traceback (most recent call last):
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/engine.py", line 926, in handler
    event = await self._handle_proposal(proposal_)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/engine.py", line 892, in _handle_proposal
    await proposal.respond(demand_builder.properties, demand_builder.constraints)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/yapapi/rest/market.py", line 165, in respond
    new_proposal = await self._subscription._api.counter_proposal_demand(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/api_client.py", line 193, in __call_api
    response_data = await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 268, in POST
    return await self.request(
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/ya_market/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 914, in start
    self._continue = None
  File "/Users/blue/.envs/yagna-python-tutorial/lib/python3.9/site-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

are those normal @nieznanysprawiciel ?

**Comment by pwalski** [comment]
Is it still happening? @shadeofblue 
What are the consequences of this error?
This second `ProposalFailed` timeout is not unusual.

**Comment by kamirr** [comment]
@shadeofblue Is this answer enough? We'd like to close the issue

**Comment by pwalski** [comment]
Closing old issue.
