### ISSUE TITLE
Error requires ctrl + c for shell

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#48]
Magda - Win+JS+???(if applicable) - Error requires ctrl + c for shell (attach )

    ```jsx
    C:\Users\ederenn\Projects\yajsapi\examples>yarn js:blender -d --subnet-tag devnet-alpha.4
    yarn run v1.22.5
    $ node ./blender/blender.js -d --subnet-tag devnet-alpha.4
    secp256k1 unavailable, reverting to browser version
    Using subnet: devnet-alpha.4
    (node:5476) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
    2021-01-19 12:57:49 [yajsapi] info: GFTP Version:0.1.2
    2021-01-19 12:58:10 [yajsapi] warn: No offers have been collected from the market for
                20s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
    2021-01-19 12:58:30 [yajsapi] warn: No offers have been collected from the market for
                40s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
    Terminate batch job (Y/N)? y

    C:\Users\ederenn\Projects\yajsapi\examples>2021-01-19 12:58:53 [yajsapi] error: read ECONNRESET
    2021-01-19 12:58:53 [yajsapi] error: Subscription - Error: read ECONNRESET

    Error: Error: read ECONNRESET
        at Subscription.events (C:\Users\ederenn\Projects\yajsapi\examples\node_modules\yajsapi\dist\rest\market.js:193:23)
        at process._tickCallback (internal/process/next_tick.js:68:7)

    2021-01-19 12:58:53 [yajsapi] error: Computation interrupted by the user.
    2021-01-19 12:58:56 [yajsapi] debug: GFTP server closed, code=null
    ```

    [yajsapi-current.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/91664c9f-8a54-40a7-be28-b04c262b6518/yajsapi-current.log)

**Comment by filipgolem** [comment]
This is a known `yarn` issue:
https://github.com/yarnpkg/yarn/issues/4667
Temporary (?) solutions:
1. run directly using node:
- JS: `node blender/blender.js`
- TS: `node ./node_modules/.bin/ts-script blender/blender.ts`
2. run using `npm`:
- `npm run ts:blender -d`

(But using `npm` for running and `yarn` for building is not great.)
