### ISSUE TITLE
yapapi - NoPaymentAccountError

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#49]
ederenn - Windows 10 +py, yacat 3.8.6  - yapapi - NoPaymentAccountError (attach `blender-yapapi.log`)

    ```jsx
    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>yagna payment fund
    Received funds from the faucet. address=0x78fc89cb3e17400e3cab7df566db3e0243d763fc

    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>yagna payment init --sender

    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>python yacat.py ?a?a?a $P$5ZDzPE45CLLhEx/72qt3NehVzwN2Ry/ --subnet-tag devnet-alpha.4 --number-of-providers 4 --log-file yacat-debug.log
    Traceback (most recent call last):
      File "yacat.py", line 7, in <module>
        from yapapi import Executor, NoPaymentAccountError, Task, WorkContext, windows_event_loop_fix
    ImportError: cannot import name 'NoPaymentAccountError' from 'yapapi' (C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\__init__.py)

    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>
    ```

    `pip install --extra-index-url [https://test.pypi.org/simple/](https://test.pypi.org/simple/) yapapi==0.5.0a2` satisfied

    ```python
    (...)
    Requirement already satisfied: certifi<2021.0.0,>=2020.6.20 in c:\users\ederenn\.envs\yagna-python-tutorial\lib\site-packages (from ya-aioclient<0.5.0,>=0.4.0->yapapi==0.5.0a2) (2020.12.5)
    Requirement already satisfied: python-dateutil<3.0.0,>=2.8.1 in c:\users\ederenn\.envs\yagna-python-tutorial\lib\site-packages (from ya-aioclient<0.5.0,>=0.4.0->yapapi==0.5.0a2) (2.8.1)
    Requirement already satisfied: six>=1.5 in c:\users\ederenn\.envs\yagna-python-tutorial\lib\site-packages (from python-dateutil<3.0.0,>=2.8.1->ya-aioclient<0.5.0,>=0.4.0->yapapi==0.5.0a2) (1.15.0)
    Requirement already satisfied: idna>=2.0 in c:\users\ederenn\.envs\yagna-python-tutorial\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<4.0,>=3.6->yapapi==0.5.0a2) (2.10)

    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>python yacat.py ?a?a?a $P$5ZDzPE45CLLhEx/72qt3NehVzwN2Ry/ --subnet-tag devnet-alpha.4 --number-of-providers 4 --log-file yacat-debug.log
    Traceback (most recent call last):
      File "yacat.py", line 7, in <module>
        from yapapi import Executor, NoPaymentAccountError, Task, WorkContext, windows_event_loop_fix
    ImportError: cannot import name 'NoPaymentAccountError' from 'yapapi' (C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\__init__.py)

    (yagna-python-tutorial) C:\Users\ederenn\Projects\yapapi\examples\yacat>
    ```

**Comment by maaktweluit** [comment]
Turns out the venv should be cleared between testing sessions.

@shadeofblue can you please add `--clear` argument to the venv commands in the handbook?

(if not in handbook, then in common issues)

**Comment by shadeofblue** [comment]
done
