### ISSUE TITLE
Failed to accept invoice (Gateway Timeout)

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/yagna-triage#84]
[blender-yapapi-cant-accept-invoice.log.gz](https://github.com/golemfactory/yagna-triage/files/6068616/blender-yapapi-cant-accept-invoice.log.gz)
[yagna-data-dir.tar.gz](https://github.com/golemfactory/yagna-triage/files/6068619/yagna-data-dir.tar.gz)

```jsx
$ examples/blender/blender.py --subnet-tag devnet-beta.1
[2021-03-02 12:26:21,016 INFO yapapi] Using log file `blender-yapapi.log`; in case of errors look for additional information there
yapapi version: 0.5.1-alpha.5
Using subnet: devnet-beta.1, payment driver: zksync, and network: rinkeby

[2021-03-02 12:26:26,909 INFO yapapi.summary] Received proposals from 1 provider so far
[2021-03-02 12:26:26,909 INFO yapapi.summary] Received proposals from 2 providers so far
[2021-03-02 12:26:26,909 INFO yapapi.summary] Received proposals from 3 providers so far
[2021-03-02 12:26:26,909 INFO yapapi.summary] Received proposals from 4 providers so far
[2021-03-02 12:26:26,910 INFO yapapi.summary] Received proposals from 5 providers so far
[2021-03-02 12:26:26,910 INFO yapapi.summary] Received proposals from 6 providers so far
[2021-03-02 12:26:26,910 INFO yapapi.summary] Received proposals from 7 providers so far
[2021-03-02 12:26:26,910 INFO yapapi.summary] Received proposals from 8 providers so far
[2021-03-02 12:26:26,910 INFO yapapi.summary] Received proposals from 9 providers so far
[2021-03-02 12:26:27,297 INFO yapapi.summary] Received proposals from 10 providers so far
[2021-03-02 12:26:28,284 INFO yapapi.summary] Agreement proposed to provider '2rec-ubuntu.b1'
[2021-03-02 12:26:28,681 INFO yapapi.summary] Agreement confirmed by provider '2rec-ubuntu.b1'
[2021-03-02 12:26:30,689 INFO yapapi.summary] Agreement proposed to provider 'azathoth-rnd.b1'
[2021-03-02 12:26:31,453 INFO yapapi.summary] Task sent to provider '2rec-ubuntu.b1', task data: 0
[2021-03-02 12:26:31,700 INFO yapapi.summary] Agreement confirmed by provider 'azathoth-rnd.b1'
[2021-03-02 12:26:32,687 INFO yapapi.summary] Task sent to provider 'azathoth-rnd.b1', task data: 10
[2021-03-02 12:26:33,706 INFO yapapi.summary] Agreement proposed to provider 'witek.b1'
[2021-03-02 12:26:34,218 INFO yapapi.summary] Agreement confirmed by provider 'witek.b1'
[2021-03-02 12:26:35,753 INFO yapapi.summary] Task sent to provider 'witek.b1', task data: 20
[2021-03-02 12:27:05,706 INFO yapapi.summary] Task computed by provider 'azathoth-rnd.b1', task data: 10
Task computed: Task(id=2, data=10), result: output_10.png, time: 0:00:33.133216
[2021-03-02 12:27:06,566 INFO yapapi.summary] Task computed by provider '2rec-ubuntu.b1', task data: 0
Task computed: Task(id=1, data=0), result: output_0.png, time: 0:00:35.506394
[2021-03-02 12:27:08,018 INFO yapapi.summary] Task sent to provider 'azathoth-rnd.b1', task data: 30
[2021-03-02 12:27:08,216 INFO yapapi.summary] Task sent to provider '2rec-ubuntu.b1', task data: 40
[2021-03-02 12:27:18,393 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x750f87d2779920820cb8d0692edb1b414c71ed98', name='azathoth-rnd.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:18 GMT')>

[2021-03-02 12:27:26,381 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x4c371f14e67d881ca60dfaf90227e41129c4f6fa', name='2rec-ubuntu.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:26 GMT')>

[2021-03-02 12:27:43,394 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x750f87d2779920820cb8d0692edb1b414c71ed98', name='azathoth-rnd.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:43 GMT')>

[2021-03-02 12:27:48,404 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x4c371f14e67d881ca60dfaf90227e41129c4f6fa', name='2rec-ubuntu.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:48 GMT')>

[2021-03-02 12:27:50,258 INFO yapapi.summary] Task computed by provider 'azathoth-rnd.b1', task data: 30
Task computed: Task(id=4, data=30), result: output_30.png, time: 0:00:44.552510
[2021-03-02 12:27:50,298 INFO yapapi.summary] Task computed by provider 'witek.b1', task data: 20
Task computed: Task(id=3, data=20), result: output_20.png, time: 0:01:14.771802
[2021-03-02 12:27:50,483 INFO yapapi.summary] Task computed by provider '2rec-ubuntu.b1', task data: 40
Task computed: Task(id=5, data=40), result: output_40.png, time: 0:00:43.917683
[2021-03-02 12:27:53,484 INFO yapapi.summary] Task sent to provider 'azathoth-rnd.b1', task data: 50
[2021-03-02 12:28:06,980 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x51b9e92efe08b51b6b1ca56973e7426060c89384', name='witek.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:28:06 GMT')>

[2021-03-02 12:28:11,761 INFO yapapi.summary] Task computed by provider 'azathoth-rnd.b1', task data: 50
Task computed: Task(id=6, data=50), result: output_50.png, time: 0:00:21.503121
[2021-03-02 12:28:11,764 INFO yapapi.summary] Computation finished in 109.9s
[2021-03-02 12:28:11,764 INFO yapapi.summary] Negotiated 3 agreements with 3 providers
[2021-03-02 12:28:11,765 INFO yapapi.summary] Provider 'azathoth-rnd.b1' computed 3 tasks
[2021-03-02 12:28:11,765 INFO yapapi.summary] Provider '2rec-ubuntu.b1' computed 2 tasks
[2021-03-02 12:28:11,765 INFO yapapi.summary] Provider 'witek.b1' computed 1 task
[2021-03-02 12:28:12,765 INFO yapapi.executor] Waiting for 3 workers to finish...
[2021-03-02 12:28:18,238 INFO yapapi.summary] Accepted invoice from 'witek.b1', amount: 0.118982862262
[2021-03-02 12:28:18,245 INFO yapapi.executor] Waiting for all services to finish...
[2021-03-02 12:28:19,697 INFO yapapi.summary] Accepted invoice from 'azathoth-rnd.b1', amount: 0.148515231356
[2021-03-02 12:28:19,908 INFO yapapi.summary] Accepted invoice from '2rec-ubuntu.b1', amount: 0.140547441324
6 tasks computed, total time: 0:01:58.653768
[2021-03-02 12:28:19,917 INFO yapapi.summary] Total cost: 0.408045534942
[2021-03-02 12:28:19,917 INFO yapapi.summary] Executor has shut downPaste logs here
```

**Comment by maaktweluit** [comment]
The message seems wrong: a debit note failed, not an invoice

**Comment by azawlocki** [comment]
Relevant snippet from the requestor log shows that the failing operation is `accept_debit_note`:
```
[2021-03-02 12:27:18,364 DEBUG ya_payment.rest] request: {'method': 'GET', 'url': 'http://127.0.0.1:7465/payment-api/v1/debitNoteEvents?afterTimestamp=2021-03-02T11%3A27%3A12.717000%2B00%3A00', 'timeout': 300, 'headers': {'Accept': 'application/json', 'authorization': 'Bearer 948ae77f0c6b49e5bbb18e372836068e', 'User-Agent': 'OpenAPI-Generator//python', 'Content-Type': 'application/json'}}
[2021-03-02 12:27:18,365 DEBUG yapapi.events] PaymentFailed(agr_id='8275ed95e205b5fd85b21149d45a68e81a1e9ac032435385ee5c44daec3a1815', exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7fcdeaeebcd0>))
Traceback (most recent call last):
  File "/home/azawlocki/golem/yapapi/yapapi/executor/__init__.py", line 338, in process_debit_notes
    amount=debit_note.total_amount_due, allocation=allocation
  File "/home/azawlocki/golem/yapapi/yapapi/rest/payment.py", line 33, in accept
    await self._api.accept_debit_note(self.debit_note_id, acceptance)
  File "/home/azawlocki/.cache/pypoetry/virtualenvs/yapapi-WUH81Zf7-py3.7/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/home/azawlocki/.cache/pypoetry/virtualenvs/yapapi-WUH81Zf7-py3.7/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/home/azawlocki/.cache/pypoetry/virtualenvs/yapapi-WUH81Zf7-py3.7/lib/python3.7/site-packages/ya_payment/rest.py", line 276, in POST
    body=body,
  File "/home/azawlocki/.cache/pypoetry/virtualenvs/yapapi-WUH81Zf7-py3.7/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:18 GMT')>

[2021-03-02 12:27:18,393 ERROR yapapi.summary] Failed to accept invoice from 'ProviderInfo(id='0x750f87d2779920820cb8d0692edb1b414c71ed98', name='azathoth-rnd.b1', subnet_tag='devnet-beta.1')', reason: (504)
Reason: Gateway Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Date': 'Tue, 02 Mar 2021 11:27:18 GMT')>
```

**Comment by Wiezzel** [comment]
Looks like network connection issues. In provider logs there are timeout errors around the same time and no trace of receiving the accept messages from this requestor. Since the error was gracefully handled here (task computed and paid successfully) I see no reason to introduce any fixes. Maybe the message from `yapapi` could be updated because it says "Failed to accept invoice" while actually failed to accept a debit note.

**Comment by Wiezzel** [comment]
@azawlocki Plz, add a task to update the error message to yapapi backlog and close this issue.

**Comment by mateuszsrebrny** [comment]
yapapi work continued here: https://github.com/golemfactory/yapapi/issues/279
closing this one
