### ISSUE TITLE
Unhandled `ya_payment.exceptions.ApiException` percolates all the way up to the requestor app

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#94]
Seen duuring today's zkSync outage:

```
 File "server.py", line 1210, in run_on_golem
    async for task in submitted_tasks:
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 213, in submit                                                           
    async for result in generator:
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 244, in _submit                                                          
    multi_payment_decoration = await self._create_allocations()
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 714, in _create_allocations                                              
    expires=self._expires + CFG_INVOICE_TIMEOUT,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/contextlib.py", line 570, in enter_async_context                                                                          
    result = await _cm_type.__aenter__(cm)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 88, in __aenter__                                                             
    new_allocation: yap.Allocation = await self._api.create_allocation(self.model)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api                                                          
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api                                                          
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 276, in POST                                                                      
    body=body,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request                                                                   
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '172', 'Content-Type': 'application/json', 'Date': 'Thu, 25 Mar 2021 17:09:24 GMT')>                             
HTTP response body: {"message":"RPC error: Error while validating allocation: Error while sending payment: Network error: Post query responded with a non-OK response: 503 Service Unavailable"}
```

Perhaps this could be handled more gracefully somewhere on the way (even if just to be reraised as a yapapi Exception)?

**Comment by mbenke** [comment]
Similar occurence last night, albeit with a different exception:

```
Traceback (most recent call last):                                                                                                                                   [5/1307]
  File "server.py", line 1721, in <module>                                                                                                                                   
    arguments.func(arguments)                                                                                                                                                
  File "server.py", line 1699, in <lambda>                                                                                                                                   
    golem_ap.set_defaults(func=lambda args: run(args, Mode.Golem))                                                                                                           
  File "server.py", line 1629, in run                                                                                                                                        
    asyncio.get_event_loop().run_until_complete(task)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete                                                                  
    return future.result()
  File "server.py", line 1420, in main
    subnet=arguments.subnet,
  File "server.py", line 1279, in run_on_golem
    async for task in submitted_tasks:
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 213, in submit                                                           
    async for result in generator:
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 244, in _submit                                                          
    multi_payment_decoration = await self._create_allocations()
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 714, in _create_allocations                                              
    expires=self._expires + CFG_INVOICE_TIMEOUT,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/contextlib.py", line 570, in enter_async_context                                                                          
    result = await _cm_type.__aenter__(cm)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 88, in __aenter__                                                             
    new_allocation: yap.Allocation = await self._api.create_allocation(self.model)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 276, in POST
    body=body,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by shadeofblue** [comment]
@mbenke we're adding this issue to our backlog and will try to handle it in the next iteration

**Comment by shadeofblue** [comment]
@mbenke it would be good to know the impact and severity though

**Comment by mateuszsrebrny** [comment]
Hopefully should be fixed by: golemfactory/yapapi#358

**Comment by mbenke** [comment]
@mateuszsrebrny I don't think golemfactory/yapapi#358 handles 503 errors like the one mentioned in this issue,.

**Comment by mateuszsrebrny** [comment]
you are right @mbenke - it is not fixed. still we are deprioritizing it for now.

**Comment by mbenke** [comment]
Got hit by this again today:

```
Traceback (most recent call last):                                                                                                                                   [4/1807]
  File "server.py", line 1924, in <module>                                                                                                                                   
    arguments.func(arguments)                                                                                                                                                
  File "server.py", line 1902, in <lambda>                                                                                                                                   
    golem_ap.set_defaults(func=lambda args: run(args, Mode.Golem))                                                                                                           
  File "server.py", line 1829, in run         
    asyncio.get_event_loop().run_until_complete(task)                 
  File "/root/miniconda3/envs/rdkit/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete                                                                  
    return future.result()                                            
  File "server.py", line 1641, in main        
    subnet=arguments.subnet,
  File "server.py", line 1409, in run_on_golem                        
    event_consumer=log_summary(log_event_repr),
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 206, in __aenter__                                                       
    await self._stack.enter_async_context(self._engine)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/contextlib.py", line 570, in enter_async_context                                                                          
    result = await _cm_type.__aenter__(cm)    
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 244, in __aenter__                                                                  
    self.payment_decorator = _Engine.PaymentDecorator(await self._create_allocations())                                                                                     
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 336, in _create_allocations                                                         
    payment_address=account.address,                                  
  File "/root/miniconda3/envs/rdkit/lib/python3.7/contextlib.py", line 570, in enter_async_context                                                                          
    result = await _cm_type.__aenter__(cm)                                                                                                                                   
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 88, in __aenter__                                                             
    new_allocation: yap.Allocation = await self._api.create_allocation(self.model)         
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api                                                          
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 276, in POST                                                                       
    body=body,                                                                                                                                                               
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 170, in request                                                                    
    r = await self.pool_manager.request(**args)                                                                                                                             
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request                                                                   
    await resp.start(conn)                                                                                                                              
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```
