### ISSUE TITLE
Computation failed, reason: (408)

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#98]
```
[2021-03-28 12:48:44,661 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_market.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f554b2d7f50\
>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 605, in _submit
    raise cast(BaseException, task.exception())
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 540, in worker_starter
    await agreements_pool.cycle()
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/agreements_pool.py", line 61, in cycle
    buffered_agreement.agreement.id, allow_reuse=task.exception() is None
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/agreements_pool.py", line 167, in release_agreement
    await self._terminate_agreement(agreement_id, reason)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/agreements_pool.py", line 177, in _terminate_agreement
    agreement_details = await buffered_agreement.agreement.details()
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", line 61, in details
    return AgreementDetails(_ref=await self._api.get_agreement(self._id))
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 205, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 201, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 198, in GET
    query_params=query_params,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Sun, 28 Mar 2021 10:48:43 GMT')>
```

**Comment by mbenke** [comment]
[yagna-210329.log.gz](https://github.com/golemfactory/yagna-triage/files/6223970/yagna-210329.log.gz)

**Comment by mbenke** [comment]
[yagna_r2021-03-28_09-07-30.log.gz](https://github.com/golemfactory/yagna-triage/files/6224011/yagna_r2021-03-28_09-07-30.log.gz)

**Comment by maaktweluit** [comment]
Market team will do the initial investigation if this is on market team / gsb / api's

**Comment by tworec** [comment]
@mbenke can you elaborate on why you perceive the `high impact` and `major severity`?

**Comment by mbenke** [comment]
@tworec re impact "most users are affected" - aborted computation means many providers are not getting paid. On top of that the (currently) biggest requestor is affected.

Re severity - almost all computations are getting aborted leading to severe performance impact (and have I mentioned, providers are not getting paid?)

**Comment by mbenke** [comment]
Another variant of this error - this time the fatal timeout is in` process_invoices`

```
[2021-04-07 13:08:51,092 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7fb493dd1140
>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 605, in _submit
    raise cast(BaseException, task.exception())
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 291, in process_invoices
    async for invoice in self._payment_api.incoming_invoices():
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 217, in fetch
    events = await api.get_invoice_events(after_timestamp=ts)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 198, in GET
    query_params=query_params,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Wed, 07 Apr 2021 11:08:49 GMT')>

[2021-04-07 13:08:51,093 ERROR yapapi.summary] Computation failed, reason: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Wed, 07 Apr 2021 11:08:49 GMT')>
```

**Comment by maaktweluit** [comment]
similar location of breaking to https://github.com/golemfactory/yagna-triage/issues/99 might be related ( but not checked )

**Comment by maaktweluit** [comment]
Monday we will assign 1 person to investigate this issue. We will scale up the eyes when this is not enough.

@tworec will get back to you on monday

**Comment by maaktweluit** [comment]
could be related to https://github.com/golemfactory/yagna/issues/1201 and https://github.com/golemfactory/yagna/issues/1205 as well

**Comment by tworec** [comment]
I was not able to analyze this until now. Sorry for delay @mbenke 
Logs you have provided have disjoint time ranges:

`yapapi` logs ( [yagna-210329.log.gz](https://github.com/golemfactory/yagna-triage/files/6223970/yagna-210329.log.gz) ) starts at 
`[2021-03-28 09:07:59,468 DEBUG yapapi] Yapapi version: 0.5.2, script: server.py, working dir(..)GolemLifeRepo`

and `yagna` logs ( [yagna_r2021-03-28_09-07-30.log.gz](https://github.com/golemfactory/yagna-triage/files/6224011/yagna_r2021-03-28_09-07-30.log.gz) ) finishes at
`[2021-03-28T07:06:54Z INFO  yagna] yagna service successfully finished!`

That's why it is not possible to match and debug them against each other. If this issue still persists (as you declared @ today's dev standup) pls attach fresh logs. together with exact versions of `yagna` and `yapapi` used (preferably commit sha's).

When running yagna pls use `RUST_LOG=debug`. This will enable us matching `yapapi` requests with what's going on under the hood within `yagna`.

**Comment by mbenke** [comment]
@tworec sorry for the wrong log. I will run recent versions with DEBUG asap, in the meantime here's a yapapi log that should fill the blanks:

[yapapi-210328.log.gz](https://github.com/golemfactory/yagna-triage/files/6323081/yapapi-210328.log.gz)

**Comment by tworec** [comment]
thank you
will look.
I think #99 also have proper logs which may fill the blanks for this one

**Comment by tworec** [comment]
The original snippet

> ```
> [2021-03-28 12:48:44,661 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_market.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f554b2d7f50
> (...)
>     await self._terminate_agreement(agreement_id, reason)
>   File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/agreements_pool.py", line 177, in _terminate_agreement
>     agreement_details = await buffered_agreement.agreement.details()
>   File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", line 61, in details
>     return AgreementDetails(_ref=await self._api.get_agreement(self._id))
> (...)
> ya_market.exceptions.ApiException: (408)
> Reason: Request Timeout
> HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Sun, 28 Mar 2021 10:48:43 GMT')>
> ```

boils down to getting `408` from get_agreement. 
File attached above  ( [yagna_r2021-03-28_09-07-30.log.gz](https://github.com/golemfactory/yagna-triage/files/6224011/yagna_r2021-03-28_09-07-30.log.gz) ) do not contain endpoint access logs because they are silenced on default log level, which you were using.  Logs from https://github.com/golemfactory/yagna-triage/issues/99#issuecomment-817571974 do contain them, but **none of over 7k** HTTP GET's for agreement
```
$ grep 'GET /market-api/v1/agreements' yagna20210411-debug.log | wc -l
    7089
```
yielded `408`:
```
$ grep 'GET /market-api/v1/agreements.* 408 ' yagna20210411-debug.log | wc -l
       0
```

Also agreement termination requests do not result with `408` but rather `200`, `410` or `500`
```
$ grep 'POST /market-api/v1/agreements.*terminate .* 200' yagna20210411-debug.log | wc -l
    1200
kinneret:~/Downloads$ grep 'POST /market-api/v1/agreements.*terminate .* 410' yagna20210411-debug.log | wc -l
    2140
kinneret:~/Downloads$ grep 'POST /market-api/v1/agreements.*terminate .* 50' yagna20210411-debug.log | wc -l
      19
kinneret:~/Downloads$ grep 'POST /market-api/v1/agreements.*terminate .*' yagna20210411-debug.log | wc -l
    3359
```

Pls collect logs with `RUST_LOG=debug` and attach if you are still experiencing this issue.

**Comment by mbenke** [comment]
@tworec Alas, github does not allow me to upload the logs - they are too big with debug (even compressed). Let's try to arrange some other transfer method.

**Comment by tworec** [comment]
`yagna` should have log rotation but access to your machine, as you've proposed is even better

**Comment by mbenke** [comment]
@tworec Access to logs granted as agreed via email.

**Comment by tworec** [comment]
There are no `408` when getting an agreement in logs provided
```
$ ls -o yagna-debug-21041*
-rw-r--r-- 1 root 28435185 Apr 17 11:23 yagna-debug-210416.log.gz
-rw-r--r-- 1 root 16570077 Apr 17 11:23 yagna-debug-210417.log.gz
golem@Debian-104-buster-64-minimal:~/logs$ zcat yagna-debug-21041*.log.gz | grep 'GET /market-api/v1/agreements' | wc -l
8166
golem@Debian-104-buster-64-minimal:~/logs$ zcat yagna-debug-21041*.log.gz | grep 'GET /market-api/v1/agreements.* 408 ' | wc -l
0
```

nor for terminating an agreement:
```
$ zcat yagna-debug-21041*.log.gz | grep 'POST /market-api/v1/agreements.*terminate' | wc -l
3734
golem@Debian-104-buster-64-minimal:~/logs$ zcat yagna-debug-21041*.log.gz | grep 'POST /market-api/v1/agreements.*terminate .* 408' | wc -l
0
```

Does that issue still occur?

**Comment by mbenke** [comment]
@tworec last seen Apr 15-16:

```
yagna-1618575188-RanGe2_C84qJH9Lu-Wk-7w.log:[2021-04-16 17:12:32,448 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 11:22:57,049 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 15:09:07,887 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 15:35:07,350 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 18:11:19,697 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 20:09:11,736 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-15 20:36:17,189 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-16 04:23:38,400 ERROR yapapi.summary] Computation failed, reason: (408)
yagna-1618472247-YORt1jIG2Sr3m0pnKagf3w.log:[2021-04-16 08:50:32,262 ERROR yapapi.summary] Computation failed, reason: (408)
```

But I am running less tasks these days to put less stress on Golem (and avoid failed computations).  At least the first occurrence mentioned in this list can be found in the provided file `yapapi-210416.log.gz`: 

```
[2021-04-16 17:12:32,421 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f5d2d9770a0>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 607, in _submit
    raise cast(BaseException, task.exception())
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 293, in process_invoices
    async for invoice in self._payment_api.incoming_invoices():
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 217, in fetch
    events = await api.get_invoice_events(after_timestamp=ts)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 198, in GET
    query_params=query_params,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Fri, 16 Apr 2021 15:12:25 GMT')>
```

I do not know what (if anything) corresponds to this event in yagna logs, but the fact remains: the computation was aborted wih error 408.

**Comment by tworec** [comment]
There is just one line within `yapapi` log containing `Computation failed, reason: (408)`:
```
$ zcat yapapi210416.log.gz | grep 'Computation failed, reason: (408)' | wc -l
1
```

it is related to getting invoice events 

```
$ zcat yapapi210416.log.gz | grep -B20 'Computation failed, reason: (408)'
[2021-04-16 17:12:32,421 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f5d2d9770a0>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 607, in _submit
    raise cast(BaseException, task.exception())
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 293, in process_invoices
    async for invoice in self._payment_api.incoming_invoices():
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/payment.py", line 217, in fetch
    events = await api.get_invoice_events(after_timestamp=ts)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 198, in GET
    query_params=query_params,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '0', 'Connection': 'close', 'Date': 'Fri, 16 Apr 2021 15:12:25 GMT')>

[2021-04-16 17:12:32,448 ERROR yapapi.summary] Computation failed, reason: (408)
```

But given `yagna` logs do not have any `408` errors for such REST API invocations. All have finished with `200` status code
```
$ zcat yagna-debug-21041* | grep 'GET /payment-api/v1/invoiceEvents' | wc -l
11509
golem@Debian-104-buster-64-minimal:~/logs$ zcat yagna-debug-21041* | grep 'GET /payment-api/v1/invoiceEvents.* 200 ' | wc -l
11509
```

I cannot investiagte it further given those logs.

@azawlocki maybe you can tell more from this yapapi log.
Pls pass your ssh public key to @mbenke (via discord or email) and he will let you in his machine.

**Comment by tworec** [comment]
I have taken a closer look at the `yagna` logs within time period around  `Computation failed, reason: (408)` happend in `yapapi` logs, which is `Fri, 16 Apr 2021 15:12:25 GMT`. My findings do not reveal anything which can explain this `408`

Here is wall of `200` HTTP responses for getting invoce events. Nothing to be worried about
```
$ zcat yagna-debug-21041* | grep '2021-04-16T15:1.*payment-api/v1/inv'
[2021-04-16T15:10:33Z INFO  actix_web::middleware::logger] 127.0.0.1:48808 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:03:57.665000%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.295907
[2021-04-16T15:17:11Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.494223
[2021-04-16T15:17:18Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.457528
[2021-04-16T15:17:24Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.513652
[2021-04-16T15:17:31Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.848230
[2021-04-16T15:17:38Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.459623
[2021-04-16T15:17:44Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.551589
[2021-04-16T15:17:50Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.424299
[2021-04-16T15:17:57Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.705791
[2021-04-16T15:18:04Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.436033
[2021-04-16T15:18:10Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.428038
[2021-04-16T15:18:16Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.415793
[2021-04-16T15:18:23Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.754978
[2021-04-16T15:18:30Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.408071
[2021-04-16T15:18:36Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.401422
[2021-04-16T15:18:42Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.405912
[2021-04-16T15:18:49Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.636376
[2021-04-16T15:18:56Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.515882
[2021-04-16T15:19:02Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.725140
[2021-04-16T15:19:09Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.427207
[2021-04-16T15:19:15Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.435184
[2021-04-16T15:19:22Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.455287
[2021-04-16T15:19:28Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.451620
[2021-04-16T15:19:35Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.455792
[2021-04-16T15:19:41Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.750609
[2021-04-16T15:19:48Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.655385
[2021-04-16T15:19:54Z INFO  actix_web::middleware::logger] 127.0.0.1:49050 "GET /payment-api/v1/invoiceEvents?afterTimestamp=2021-04-16T15:17:06.217539%2B00:00 HTTP/1.1" 200 2 "-" "OpenAPI-Generator//python" 5.474749
```

When I filtered all payment-api interactions within this period there is single non `20X` HTTP status code
```
$ zcat yagna-debug-21041* | grep '2021-04-16T15:1.*payment-api' | grep -v ' 20[0-9] '
[2021-04-16T15:12:37Z INFO  actix_web::middleware::logger] 127.0.0.1:45084 "POST /payment-api/v1/debitNotes/fa910793-3456-4d76-be5c-1cecf329d404/accept HTTP/1.1" 504 0 "-" "OpenAPI-Generator//python" 5.126242
```

But it is related to debit note acceptance, and it is `504` not `408`. 

So I really cannot trace anything more here releated to original issue reported which is `Computation failed, reason: (408)`.

Maybe I'm not properly interpreting `yapapi` logs. @azawlocki can you help?

**Comment by mbenke** [comment]
In any case, I am still being hit by this error:

```
[2021-04-25 11:44:40,438 ERROR yapapi.summary] Computation failed, reason: (408)
[2021-04-25 12:21:42,587 ERROR yapapi.summary] Computation failed, reason: (408)
[2021-04-25 13:13:34,330 ERROR yapapi.summary] Computation failed, reason: (408)
```

yagna 0.6.4, yapapi from b0.5 branch (346f22c )

**Comment by mbenke** [comment]
@tworec while I can not see anything in the yagna logs either, I have a theory why: 408 means timeout, i.e. yagna DID NOT respond in time hence there is no trace in the yagna logs.

I am curious what @azawlocki has to say too, but please do not give up on this bug yet.

**Comment by tworec** [comment]
> @tworec while I can not see anything in the yagna logs either, I have a theory why: 408 means timeout, i.e. yagna DID NOT respond in time hence there is no trace in the yagna logs.
> 
> I am curious what @azawlocki has to say too, but please do not give up on this bug yet.

I suspect the very same.

**Comment by azawlocki** [comment]
@mbenke @tworec 
Relevant `yapapi` issue: https://github.com/golemfactory/yapapi/issues/353
A fix: https://github.com/golemfactory/yapapi/pull/354

**Comment by tworec** [comment]
Yay! Thx

**Comment by tworec** [comment]
Closing this via https://github.com/golemfactory/yapapi/pull/358 and https://github.com/golemfactory/yapapi/pull/354
